### ISSUE TITLE
broken markup on ckanext-dcat doc page

### ISSUE THREAD

**Issue by VladimirAlexiev** [ckan/extensions.ckan.org#104]
Look at the bottom of section http://extensions.ckan.org/extension/dcat/#dataset-endpoints: the markup is broken. The breakage starts like this:
```
 ```xml
```
and then goes on to
```
Another example:
  ``` @prefix dcat: http://www.w3.org/ns/dcat# . @prefix dct: http://purl.org/dc/terms/ . @prefix rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns# .
```
There is no such breakage at https://github.com/ckan/ckanext-dcat/blob/master/README.md#rdf-dcat-to-ckan-dataset-mapping.

So I think the MD renderer is a little defective.

**Comment by jqnatividad** [comment]
Hi @VladimirAlexiev, thanks for this bug report.  

We're now using pandoc to "normalize" markdown as well.  Before, we were only using pandoc to convert RST to github-flavored markdown.

Since the catalog is hosted on github pages, MD that renders on GH, may not necessarily render in the same way using the Jekyll kramdown renderer that GH pages uses.

https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
