### ISSUE TITLE
Add ckanext-openapiviewer

### ISSUE THREAD

**Issue by jqnatividad** [ckan/extensions.ckan.org#115]
Hi @banders!

Recently found your project and would love to socialize it with the CKAN ecosystem.

Is it OK? If so, please let tweak the catalog entry below.

Thanks!

Extension URL: https://github.com/bcgov/ckanext-openapiviewer
Extension Author(s): Province of British Columbia
Compatibility: 2.3+ 
Title: OpenAPI (AKA Swagger) console for CKAN resources that are web services
Name (Unique): openapiviewer

**Comment by gjlawran** [comment]
Hi @jqnatividad !
Please feel free to add our openapiviewer extension to the list of extensions. I created a new issue and then I just saw your issue.  

I guess I could also add an example implementation site

[https://catalogue.data.gov.bc.ca/dataset/bc-data-catalogue-api](https://catalogue.data.gov.bc.ca/dataset/bc-data-catalogue-api)

 to the extension readme so that people can see it in action.

**Comment by jqnatividad** [comment]
This is awesome! This will make developing for CKAN much easier and even localizes the examples to the data for that instance. Thanks!
