### ISSUE TITLE
Add Extension ckanext-irods

### ISSUE THREAD

**Issue by rossjones** [ckan/extensions.ckan.org#33]
Repo: https://github.com/kata-csc/ckanext-irods

This plugin enables a user to pull in information from a collection in iRODS or
from a separate file into a dataset.

**Comment by jqnatividad** [comment]
Hi @rossjones, its already in [Master Extension List](https://docs.google.com/a/ontodia.com/spreadsheets/d/1izCpljO6Et7zLUKcUlB4BzsMZTurENp56Iqi9kXOtgs/edit#gid=0), but the status is unknown, that's why its not in the extension registry.

Do you know what version of CKAN its been tested on and if its still maintained?
