### ISSUE TITLE
Add Extension ckanext-dictionary

### ISSUE THREAD

**Issue by mcleinman** [ckan/extensions.ckan.org#81]
Extension URL: https://github.com/cmuphillycapstone/ckanext-dictionary
Extension Author(s): Heinz/CMU Capstone Team
Compatibility: All versions with two current stages in 'add dataset' dialog'; requires DataStore extension to also be installed
Title: Data Dictionaries for Datasets
Name: ckanext-dictionary

**Comment by jqnatividad** [comment]
Thanks for this much needed contribution.  I'm sure a lot of PA-based installations will be very interested cc @rgradeck @timwis.

**Comment by rgradeck** [comment]
Thanks - Interested in learning more about the project, too.
]

**Comment by timwis** [comment]
Hey @jqnatividad I've searched for `dictionary` on extensions.ckan.org a few times and it doesn't seem to show up. Am I doing something wrong?

**Comment by jqnatividad** [comment]
Right now, search only works on the title of the extension.  And since ckanext-dictionary's title is "Data Dictionaries for Datasets", it doesn't find it. (try "dictiona")

There's an open ticket to improve search (#23) so it searches everything.  I actually started scratching it over the snow-bound weekend.  Will ping you once its done.

**Comment by timwis** [comment]
got it - thanks!
